@ECHO OFF
SETLOCAL

REM
REM Enable windows installer logging
REM    msiexec /i "C:\temp\installer.msi" /L*V "C:\temp\file.log"

ECHO [93m*** ENVIRONMENT CHECK ***[0m
wmic product get name | findstr /c:"WiX Toolset v3.11" > NUL
IF %ERRORLEVEL% NEQ 0 (
  ECHO [91mWix Toolset build tools not installed - download from https://wixtoolset.org/[0m
  GOTO :error
)
ECHO Passed

SET arch=x64
SET selfcontained=true
SET publishmode=SELFCONTAINED
SET configuration=Release
SET version="0.0.0.999-DEV"& :: Do not change, see also <InformationalVersion> on Bravo.csproj 
SET verbosity="Minimal"& :: Minimal,Normal,Diagnostic,Detailed
SET wixheat="%WIX%bin\heat.exe"
SET wixlight="%WIX%bin\light.exe"
SET wixcandle="%WIX%bin\candle.exe"
SET msbuild="%WINDIR%\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe"
SET publishfolder=%~dp0src\bin\_publish
SET wixpublishfolder=%publishfolder%\wix
SET dotnetpublishfolder=%publishfolder%\dotnet

IF EXIST "%publishfolder%" RMDIR /s /q "%publishfolder%"

ECHO [93m*** BRAVO - PUBLISH ***[0m
CD /d "%~dp0"
dotnet publish Bravo.sln --configuration %configuration% --output "%dotnetpublishfolder%" --self-contained %selfcontained% --verbosity %verbosity% --nologo /p:AdditionalConstants=%publishmode% || GOTO :error

ECHO [93m*** BRAVO - BUILD INSTALLER ***[0m
CD /d "%~dp0installer\wix\src\Bravo"
%wixheat% dir "%dotnetpublishfolder%" -gg -scom -srd -sreg -sfrag -templatefragment -cg ComponentsAutogenerated -dr INSTALLFOLDER -var var.PublishFolder -t Bravo.xslt -out Components.autogenerated.wxs -nologo || GOTO :error
%wixcandle% Components.autogenerated.wxs -arch %arch% -dPublishFolder="%dotnetpublishfolder%" -nologo || GOTO :error
%wixcandle% Bravo.wxs -arch %arch% -dPublishFolder="%dotnetpublishfolder%" -dVersion="%version%" -nologo || GOTO :error
%wixcandle% Bravo-perUser.wxs -arch %arch% -dPublishFolder="%dotnetpublishfolder%" -dVersion="%version%" -nologo || GOTO :error
REM light -sice:ICE03 is used to ignore -> warning LGHT1076 : ICE03: String overflow (greater than length permitted in column). These warnings are expected and can be safely ignored
REM light -sice:ICE57 is used to ignore -> error   LGHT0204 : ICE57: Component 'app.exe' has both per-user and per-machine data with a per-machine KeyPath.
REM light -sice:ICE60 is used to ignore -> warning LGHT1076 : ICE60: The file filE8E88FBC49DC5621FF3FC1B65ADCCB39 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
REM light -sice:ICE61 is used to ignore -> warning LGHT1076 : ICE61: This product should remove only older versions of itself. The Maximum version is not less than the current product.
REM light -sice:ICE80 is used to ignore -> error   LGHT0204 : ICE80: This 64BitComponent pbitool.json uses 32BitDirectory POWERBIEXTERNALTOOLSFOLDER
%wixlight% Bravo.wixobj Components.autogenerated.wixobj -ext WixUIExtension.dll -ext WixUtilExtension.dll -cultures:en-us -loc Bravo-en-us.wxl -out "%wixpublishfolder%\Bravo-%arch%-en-us.msi" -sice:ICE03 -sice:ICE60 -sice:ICE61 -sice:ICE80 -nologo || GOTO :error
%wixlight% Bravo-perUser.wixobj Components.autogenerated.wixobj -ext WixUIExtension.dll -ext WixUtilExtension.dll -cultures:en-us -loc Bravo-en-us.wxl -out "%wixpublishfolder%\Bravo-%arch%-en-us-userinstaller.msi" -sice:ICE57 -sice:ICE60 -sice:ICE61 -sice:ICE80 -nologo || GOTO :error

REM ECHO ***
REM ECHO *** STORELAUNCHER BUILD ***
REM ECHO ***
REM SET publishfolder=%~dp0installer\msix\Bravo.Installer.Msix.StoreLauncher\bin\%configuration%
REM CD /d "%~dp0installer\msix\Bravo.Installer.Msix.StoreLauncher"
REM %msbuild% /target:Clean;Rebuild /property:Configuration=%configuration% /verbosity:%verbosity% /toolsversion:4.0 /nologo Bravo.Installer.Msix.StoreLauncher.csproj || GOTO :error

REM ECHO ***
REM ECHO *** STORELAUNCHER INSTALLER ***
REM ECHO ***
REM CD /d "%~dp0installer\wix\src\BravoStoreLauncher"
REM IF EXIST *.msi    DEL *.msi
REM IF EXIST *.wixobj DEL *.wixobj
REM IF EXIST *.wixpdb DEL *.wixpdb
REM %wixcandle% BravoStoreLauncher.wxs -arch "%arch%" -dPublishFolder="%publishfolder%" -dVersion="%version%" -nologo || GOTO :error
REM REM light -sice:ICE61 is used to ignore -> warning LGHT1076 : ICE61: This product should remove only older versions of itself. The Maximum version is not less than the current product.
REM REM light -sice:ICE80 is used to ignore -> error LGHT0204 : ICE80: This 64BitComponent pbitool.json uses 32BitDirectory POWERBIEXTERNALTOOLSFOLDER
REM %wixlight% BravoStoreLauncher.wixobj -ext WixUIExtension.dll -cultures:en-us -loc BravoStoreLauncher-en-us.wxl -out "BravoStoreLauncher-%arch%-en-us.msi" -sice:ICE61 -sice:ICE80 -nologo || GOTO :error

ECHO [42m*** PUBLISH COMPLETED ***[0m
GOTO :EOF

:error
ECHO [101m*** PUBLISH FAILED ***[0m
EXIT /b %ERRORLEVEL%